name: Dune Alert Bot

on:
  workflow_dispatch:  # allows manual execution
  schedule:
    - cron: "0 * * * *"  # runs every hour

jobs:
  run-alert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the alert script
        env:
          DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python jupiter_trading_volume_ath_alert_dune_api_integration_2.py
