name: Dune Alert Script

on:
  schedule:
    - cron: '0 12 * * 1'  # toda segunda-feira às 12:00 UTC
  workflow_dispatch:      # permite executar manualmente pelo GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        env:
          DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python jupiter_trading_volume_ath_alert_dune_api_integration_2.py
